backend:
  build: backend
  volumes:
    - "./backend:/app"
  ports:
    - "8888:8888"
  environment:
    PYTHONUNBUFFERED: 1
  command: python manage.py runserver 0.0.0.0:8888
  links:
    - "db"

frontend:
  build: frontend
  volumes:
    - "./frontend:/app"
  ports:
    - "3000:3000"
    - "3001:3001"
  command: npm start

nginx:
  image: nginx
  links:
    - backend
    - frontend
  ports:
    - "9999:9999"
  volumes:
    - "./nginx/insta.conf:/etc/nginx/conf.d/insta.conf"

db:
  image: postgres
  environment:
    POSTGRES_PASSWORD: instalytics
    POSTGRES_USER: instalytics
    POSTGRES_DB: instalytics
  volumes:
    - "/usr/lib/instalytics:/var/lib/postgresql/data"
