# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-13 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('target', models.IntegerField(choices=[(0, 'Bio'), (1, 'URL'), (2, 'Avatar')])),
                ('value', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.InstaUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='change',
            name='user',
        ),
        migrations.DeleteModel(
            name='Change',
        ),
    ]
