# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-13 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20160613_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='instauser',
            name='biography',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='instauser',
            name='external_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='instauser',
            name='full_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='instauser',
            name='profile_pic_url',
            field=models.URLField(blank=True),
        ),
    ]
